### ISSUE TITLE
Error: socket not connected after call to logout() - RTM API

### ISSUE THREAD

**Issue by AB-70** [livechat/lc-sdk-js#128]
Hi, I have been getting this error after calling logout() function of the RTM API. Despite having all my methods with catch().. and try-catch blocks. It seems like one of the internal methods is calling the 'send' function asynchronously which results in the app to crash. 

After reviewing the source code it appears that the problem is caused by the `heartbeatInterval `timeout calling the 'send' function in a promise without handling the error itself or calling reject on the parent promise (returned  by connect()) 

https://github.com/livechat/lc-sdk-js/blob/66c34acf5f42e0bbff7fbd524918bb5b12728d1b/src/internal/index.ts#L121C1-L121C1

Thanks! 

ERROR
```
node_modules\@livechat\lc-sdk-js\lib\src\internal\index.js:148
            return Promise.reject(new Error("socket not connected"));
                                  ^

Error: socket not connected
    at RTM.send (E:\Projects\Clients\PropFirms\newpfm\livechat-agent\node_modules\@livechat\lc-sdk-js\lib\src\internal\index.js:148:35)
    at Timeout._onTimeout (E:\Projects\Clients\PropFirms\newpfm\livechat-agent\node_modules\@livechat\lc-sdk-js\lib\src\internal\index.js:109:65)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.17.1
```

**Comment by AB-70** [comment]
Okay, I can't even use this one now. Says I don't have a license for developer API. Guess I gotta wait this now until it's fixed officially which I don't think will be any soon. 😫

**Comment by wfabjanczuk** [comment]
Hi @AB-70, thank you for reporting the bug. 

> After reviewing the source code it appears that the problem is caused by the heartbeatInterval timeout calling the 'send' function in a promise without handling the error itself or calling reject on the parent promise (returned by connect())

You are right, there is an unhandled promise rejection in the heartbeat interval and I've prepared a fix for that in the PR https://github.com/livechat/lc-sdk-js/pull/130.

> Okay, I can't even use this one now. Says I don't have a license for developer API. Guess I gotta wait this now until it's fixed officially which I don't think will be any soon. 😫

There are 2 things here:

- The v3.6 version is still in dev preview stage and only the approved developers can use it. If you wish to use it, let me know and I can arrange that. Also, due to an error the [documentation](https://platform.text.com/docs/messaging#api-versioning) says that it is already stable/legacy - we will fix that.
- The latest stable version of our JS SDK is v3.5 (npm version [5.2.0](https://www.npmjs.com/package/@livechat/lc-sdk-js/v/5.2.0)) and once the PR https://github.com/livechat/lc-sdk-js/pull/130 is reviewed and accepted, the fix will be added to the [v3.5](https://github.com/livechat/lc-sdk-js/commit/cadf371ad7b5e81202b4ee22c89413c2492493c5) and the rest of working SDK versions.

For now I suggest either:

- using the SDK at https://github.com/livechat/lc-sdk-js/commit/cadf371ad7b5e81202b4ee22c89413c2492493c5 (v3.5 version with the upcoming fix),
- or connecting to the [Agent RTM API](https://platform.text.com/docs/messaging/agent-chat-api/rtm-reference) or [Customer RTM API](https://platform.text.com/docs/messaging/customer-chat-api/rtm-reference) directly without the use of the SDK.

Let me know if it helps and also check out our Discord for developers: https://discord.gg/MGFyhbdFxt

**Comment by wfabjanczuk** [comment]
Hi again, the fixes have been merged and npm versions have been updated.

The latest [npm version is 5.3.0](https://www.npmjs.com/package/@livechat/lc-sdk-js) which corresponds to our latest stable [API version v3.5](https://platform.text.com/docs/messaging/agent-chat-api).

**Comment by wfabjanczuk** [comment]
@AB-70 Let me know if everything works for you now

**Comment by AB-70** [comment]
Thank you, will let you know if I face any issues after updating to the latest version.
